### ISSUE TITLE
Repo is missing tagged versions and Releases

### ISSUE THREAD

**Issue by jasonkarns** [perezd/node-murmurhash#5]
Missing tags for the two releases on npm

![image](https://user-images.githubusercontent.com/119972/79020110-ee592180-7b45-11ea-8836-2110ae39430b.png)

**Comment by perezd** [comment]
Those are now pre-version 1.0 releases, and therefore have no warranty. welcome to 1.0!

**Comment by jasonkarns** [comment]
lol 
![image](https://user-images.githubusercontent.com/119972/79025351-798ce400-7b53-11ea-9a84-0f9753bdcd20.png)

love this.
