### ISSUE TITLE
Consider to use TextEncoder to support browsers and node

### ISSUE THREAD

**Issue by barak007** [perezd/node-murmurhash#7]
Hey,
I am using this library and when I started to move to webpack 5 (when they stopped polyfill node apis) I notice that it using node Buffer to process the `key`.

now days there is the TextEncoder API in node and browser and from simple tests it seems like providing the same results can you please consider using it to support both node and browser?

TextEncoder 
v11.0.0 | The class is now available on the global object.
v8.3.0 | Added in: v8.3.0

I can also open a PR.

**Comment by perezd** [comment]
Sure, a PR would be great!

**Comment by barak007** [comment]
Do you still want to support old node versions? 
node 14.15.0 is now LTS

by the way I see the original implementation uses `charCodeAt` and accept a string as key any reason to use Buffer?

**Comment by perezd** [comment]
This was just a port of the original code, I didn't write it so its as close to the original as possible. Feel free to add alternate API signatures but don't change the existing ones for compatibility reasons for others. I'm OK with bumping to new LTS and we'll do a version rev to signify that.
